### ISSUE TITLE
Issue with Image and Screen not displaying properly - no animation

### ISSUE THREAD

**Issue by Marebears** [konsumer/animillusion#1]
![capture](https://user-images.githubusercontent.com/23286661/43230582-74ffb406-902e-11e8-9bbb-bda7a58ad92b.JPG)
![capture2](https://user-images.githubusercontent.com/23286661/43230592-78144954-902e-11e8-99b9-b96071ef0bd9.JPG)

The large image and screen for the three example (and uploaded) image sets will not load properly. The image and screen are offset and small. Tried with 3 different browsers

**Comment by konsumer** [comment]
wow, it's been a long time since I worked on this. I will take a look. It did work at one time.

**Comment by konsumer** [comment]
looks like the last hash that works is before fancy DND and other things (6e95316). Maybe I should just remake it as a react app.

![2018-07-26 18 01 50](https://user-images.githubusercontent.com/83857/43296093-08128046-90fe-11e8-95cb-4bb83bfd7e08.gif)

**Comment by konsumer** [comment]
Ok! added [react demo](http://konsumer.js.org/animillusion/) (that you can use with file drag & drop to generate images) and building/packaging so it's easier to use it in your own thing.  Marking closed, but feel free to comment more, here, if you have issues

**Comment by Marebears** [comment]
Tried dropping in a few different images and it seems to have removed or masked over the slots image. The default cat image does work though. Thanks for working on this btw!

**Comment by konsumer** [comment]
now, it scrolls differently, but it works with everything I have:
![2018-07-28 20 49 00](https://user-images.githubusercontent.com/83857/43362799-b560c42e-92a7-11e8-9fe1-a604cd9fc1ff.gif)
